### ISSUE TITLE
Take photos!

### ISSUE THREAD

**Issue by lukeaparker** [MAP-Team/data-science#6]
- [x] Make sure the raspberry pi is set up
 * https://raspberrypi.stackexchange.com/questions/14229/how-can-i-enable-the-camera-without-using-raspi-config
- [x] Take a couple of pictures with the raspberry pi
 * https://howchoo.com/g/zjy0nwviodl/how-to-take-a-picture-with-your-raspberry-pi

**Comment by TasfiaAddrita** [comment]
- [ ] opencv stereoscopic vision
- https://docs.opencv.org/master/dd/d53/tutorial_py_depthmap.html

**Comment by lukeaparker** [comment]
Took photos through raspi, setup now for testing.
